### PR TITLE
AddStatement 1st version & stuff

### PR DESCRIPTION
**Pull request by wiztigers**
Hi Laurent,

Here are some changes that could use some revewing and pushing on your master branch :)

Regards

### CODE REVIEW

**Comment by wiztigers** [comment]
6a8d49a should be refactored soon
- when identifiers and literals will be done
- to allow detection of 2nd operand-should-not-be-literal-because-there-s-no-GIVING error and such

**Comment by laurentprudhon** [comment]
Thank you for your contribution, but I can't merge all the commits right now.
Please see the comments I attached to each one of the 4 commits, and to some significant source code lines.

**Comment by laurentprudhon** [comment]
Recommended video :
[Using Git in Visual Studio 2015](https://channel9.msdn.com/Events/Build/2015/3-746)

**Comment by wiztigers** [comment]
AddStatement is not yet refactored into Expression class, but I made some progress in making grammar rules more explicit as long as unit testing this feature.

Besides, this made me wondering about some grammar shenanigans I encountered while digging into .g4 files. I'm a bit unsure about some intents and inner workings of ANTLR.

In short: the goal of this commit is not to close the request, but to show progress.

**Comment by wiztigers** [comment]
That's just a first proposal for class Expression and children.
There must be a better way to represent identifiers and litterals. I'll study this next week as long as the rules for these.

See you next week ! ᶘ ᵒᴥᵒᶅ

**Comment by wiztigers** [comment]
The 3 ADD formats are now implemented, and I added more unit testing (compare the built token tree vs Reversed Polish Notation).
I now have to figure out how to manage syntax errors. However, I feel this pull request is mergeable as is, isn't it ?

**Comment by laurentprudhon** [comment]
There are still TODOs, notably :
- handle ZERO figurative constant
- replace literal by numericLiteral if it makes sense
- full parsing of identifier rule
- correct expressions trees

But I feel this is explicit enough in the code and we can merge this pull request.

**Comment by wiztigers** [comment]
Thanks for the merge !

Good point!
I've created the 3 first issues in my repo https://github.com/wiztigers/TypeCobol/issues
However I'm not sure about the meaning of the 4th one.

**Pull request merged**
